HOFF-639 Update RIL to HOF v20.4.0
UKHomeOffice/refugee-integration-loan pull request #22
Opened 2024-03-05 11:42 UTC by TemitopeAyokuHO

## What?
- [HOFF-639 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-639).- changing Queen's crown to King's crown logo
- added ignore failure flag for accessibility test in drone.yaml
- updated pa11y to version 7.

## Why?
- The Gov.uk crown logo changed
- To pass drone build -  Accessibility test failed on Branch due to pa11y. Pa11y needs update to [Version 8](https://github.com/pa11y/pa11y/pull/689.) release date unknown
 
## How?
- yarn add hof@20.4.0
- updated pa11y in package.json
- added ignore failure flag for accessibility test in drone.yaml

## Testing?
Tested locally
 Accessibility test failed on Branch , Pa11y needs update to [Version 8](https://github.com/pa11y/pa11y/pull/689.) release date unknown
## Screenshots (optional)
 
![Screenshot 2024-02-29 at 17 21 12](https://github.com/UKHomeOffice/refugee-integration-loan/assets/138882912/fafa4c57-6dfa-4f3b-9e6c-778672f91804)

2024-03-05 23:36 UTC, Rhodine-orleans-lindsay requested changes

2024-03-05 23:36 UTC, Rhodine-orleans-lindsay commented on package-lock.json
Please delete this file - we use yarn.lock so don't need package-lock.json(it was probably created by running ```npm install```  instead of ```yarn```)

2024-03-06 09:15 UTC, TemitopeAyokuHO commented on package-lock.json
removed

2024-03-13 10:22 UTC, TemitopeAyokuHO commented
Accessibility test failed, Pa11y needs update to  [version 8](https://github.com/pa11y/pa11y/pull/689.) release date unknown

2024-03-18 12:38 UTC, Rhodine-orleans-lindsay approved these changes

2024-03-18 12:43 UTC, merged